export enum PtBr {
  title = 'Calculadora de Tempo Profético',
  toTypeTime = 'Digite um tempo literal',
  second = 'Segundo',
  seconds = 'Segundos',
  minute = 'Minuto',
  minutes = 'Minutos',
  hour = 'Hora',
  hours = 'Horas',
  day = 'Dia',
  days = 'Dias',
  week = 'Semana',
  weeks = 'Semanas',
  month = 'Mês',
  months = 'Mêses',
  year = 'Ano',
  years = 'Anos',
  result = 'Resultado',
  literalEquals = 'literal equivale',
  literalsEquals = 'literais equivale',
  prophetic = 'profético',
  prophetics = 'proféticos',
}
